### ISSUE TITLE
Support symfony/cache 7.0

### ISSUE THREAD

**Issue by dqualmann** [storyblok/storyblok-php-client#102]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Symfony released v7 in November 2023. This project is currently limited to using symfony/cache up to v6.

---

It is possible to add symfony/cache:7 to allowed versions?

**Comment by roberto-butti** [comment]
Hi @dqualmann , I've just tagged the 2.6.3 release. Please feel free to use it ,and let me know any feedback. 
Enjoy programming with Symfony 7 :)
https://github.com/storyblok/storyblok-php-client/releases/tag/v2.6.3
