### ISSUE TITLE
Client->getStories not respecting release  

### ISSUE THREAD

**Issue by hoersamu** [storyblok/storyblok-php-client#92]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Currently the getStories function does not set the from_release query parameter for requests to Storyblok if the release was set using the setRelease function.

## Expected Behavior

The getStories function should add the release parameter correctly if $this->release is set.

## Current Behavior

The release parameter is not set when calling the getStories function if it isn't provided using the options parameter

## Steps to Reproduce

Not working 
```php
$client = new Client('api-key-###');
$client->setRelease('123456');
$options = [
  'by_slugs' => 'test'
];
$client->getStories($options);
```

Workaround
```php
$client = new Client('api-key-###');
$options = [
  'by_slugs'     => 'test',
  'from_release' => '123456'
];
$client->getStories($options);
```

I don't mind creating a fix PR, but your contributing guidelines said to open an issue first.

**Comment by roberto-butti** [comment]
Thank you, @hoersamu, for reporting the issue.
I think that for consistency with other methods like setLanguage() etc is a good option to make the setReleases() work. I see you already opened the PR. I'm jumping on the PR.
Thank you for the feedback!

Roberto
